version: '2'
services:
  golang:
    build: golang
    command: >
      go run main.go
    working_dir: /root/go/app
    volumes:
      - ./app:/root/go/app
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - GO111MODULE=on
    tty: true
  db:
    image: mysql:8.0.16
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: golang_webapp
      MYSQL_ROOT_PASSWORD: mysql
      